"use client"

import { DotPattern } from "@/components/dot-glyph"

// Small, monochrome interpretations of service marks, struck on the same dot
// grid as the room. The service name beside each icon supplies its label.
export const SERVICE_GLYPHS = {
  "google-tasks": [
    "...XXXXX...",
    "..X.....X..",
    ".X.......X.",
    "X.......X.X",
    "X......X..X",
    "X.X...X...X",
    "X..X.X....X",
    "X...X.....X",
    ".X.......X.",
    "..X.....X..",
    "...XXXXX...",
  ],
  "google-calendar": [
    "..X.....X..",
    ".XXXXXXXXX.",
    ".XX.....XX.",
    ".XXXXXXXXX.",
    ".X.......X.",
    ".X.XX..X.X.",
    ".X..X.XX.X.",
    ".X.XX..X.X.",
    ".X..X..X.X.",
    ".X.XX..X.X.",
    ".XXXXXXXXX.",
  ],
  todoist: [
    ".XXXXXXXXX.",
    "X.........X",
    "X.....X...X",
    "X.X..X....X",
    "X..XX..X..X",
    "X.X...X...X",
    "X..XXX..X.X",
    "X.X....X..X",
    "X..XXXX...X",
    "X.........X",
    ".XXXXXXXXX.",
  ],
  "microsoft-todo": [
    "...........",
    ".......XX..",
    "......XXX..",
    ".....XXX...",
    "XX..XXX..X.",
    "XXXXXX..XX.",
    ".XXXX..XX..",
    "..XX..XX...",
    ".....XX....",
    "....XX.....",
    "...........",
  ],
  "outlook-calendar": [
    ".....X..X..",
    "....XXXXXXX",
    "....X.....X",
    "....XXXXXXX",
    ".XXXXX....X",
    "XX...XX.X.X",
    "XX.X.XX...X",
    "XX.X.XX.X.X",
    "XX...XX...X",
    ".XXXXX....X",
    "....XXXXXXX",
  ],
  notion: [
    ".XXXXXXXXX.",
    "X.........X",
    "X.XX....X.X",
    "X.XXX...X.X",
    "X.X.XX..X.X",
    "X.X..XX.X.X",
    "X.X...XXX.X",
    "X.X....XX.X",
    "X.X.....X.X",
    "X.........X",
    ".XXXXXXXXX.",
  ],
  linear: [
    "...XXXXX...",
    "..XXXXXXX..",
    ".XXXXXXXXX.",
    "X.XXXXXXXXX",
    "XX.XXXXXXXX",
    "X.X.XXXXXXX",
    "XX.X.XXXXXX",
    "XXX.X.XXXXX",
    ".XXX.X.XXX.",
    "..XXX.X.X..",
    "...XXX.X...",
  ],
  github: [
    ".XX.....XX.",
    ".XXX...XXX.",
    ".XXXXXXXXX.",
    "XXXXXXXXXXX",
    "XXX.XXX.XXX",
    "XXXXXXXXXXX",
    ".XXXXXXXXX.",
    "...XXXXX...",
    "XX..XXX....",
    ".XXXXXX....",
    "....XXX....",
  ],
  trello: [
    ".XXXXXXXXX.",
    "X.........X",
    "X.XX.XXX..X",
    "X.XX.XXX..X",
    "X.XX.XXX..X",
    "X.XX.XXX..X",
    "X.XX.XXX..X",
    "X.XX......X",
    "X.XX......X",
    "X.........X",
    ".XXXXXXXXX.",
  ],
  asana: [
    "....XXX....",
    "...XXXXX...",
    "...XXXXX...",
    "...XXXXX...",
    "....XXX....",
    "...........",
    ".XXX...XXX.",
    "XXXXX.XXXXX",
    "XXXXX.XXXXX",
    "XXXXX.XXXXX",
    ".XXX...XXX.",
  ],
  gmail: [
    "...........",
    "XX.......XX",
    "XXX.....XXX",
    "XXXX...XXXX",
    "XX.XX.XX.XX",
    "XX..XXX..XX",
    "XX...X...XX",
    "XX.......XX",
    "XX.......XX",
    "XX.......XX",
    "...........",
  ],
  "outlook-mail": [
    "...........",
    "....XXXXXXX",
    "....XX...XX",
    ".XXXXXX.X.X",
    "XX...XXX..X",
    "XX.X.XX...X",
    "XX.X.XX...X",
    "XX...XX.X.X",
    ".XXXXX...XX",
    "....XXXXXXX",
    "...........",
  ],
  slack: [
    ".XX.XX.....",
    ".XX.XX.....",
    "....XX.....",
    "XXXXXX.XXXX",
    "XXXXXX.XXXX",
    "...........",
    "XXXX.XXXXXX",
    "XXXX.XXXXXX",
    ".....XX....",
    ".....XX.XX.",
    ".....XX.XX.",
  ],
  discord: [
    "...........",
    "..XX...XX..",
    ".XXXXXXXXX.",
    ".XXXXXXXXX.",
    "XXXXXXXXXXX",
    "XXX.XXX.XXX",
    "XXX.XXX.XXX",
    "XXXXXXXXXXX",
    "XXXX...XXXX",
    ".XX.....XX.",
    "...........",
  ],
  obsidian: [
    ".....X.....",
    "....XXX....",
    "...XX.XX...",
    "..XX..XXX..",
    ".XX...XXXX.",
    ".XX...XXX..",
    ".XX..XXX...",
    "..XX.XXX...",
    "...XXXXX...",
    "....XXX....",
    ".....X.....",
  ],
  "apple-calendar": [
    "..X.....X..",
    ".XXXXXXXXX.",
    "XXXXXXXXXXX",
    "XXXXXXXXXXX",
    "X.........X",
    "X.XX...X..X",
    "X...X.XX..X",
    "X.XX...X..X",
    "X...X..X..X",
    "X.XX..XXX.X",
    ".XXXXXXXXX.",
  ],
  "apple-reminders": [
    ".XXXXXXXXX.",
    "X.........X",
    "X.X.XXXXX.X",
    "X.........X",
    "X.........X",
    "X.X.XXXXX.X",
    "X.........X",
    "X.........X",
    "X.X.XXXXX.X",
    "X.........X",
    ".XXXXXXXXX.",
  ],
  files: [
    ".XXXXXX....",
    ".X....XX...",
    ".X....X.X..",
    ".X....XXXX.",
    ".X.......X.",
    ".X.XXXXX.X.",
    ".X.......X.",
    ".X.XXXXX.X.",
    ".X.......X.",
    ".X.......X.",
    ".XXXXXXXXX.",
  ],
  n8n: [
    "........XX.",
    ".......X..X",
    "......X.XX.",
    "......X....",
    ".XX..XX....",
    "X..XX..X...",
    ".XX..XX....",
    "......X....",
    "......X.XX.",
    ".......X..X",
    "........XX.",
  ],
  zapier: [
    "....XXX....",
    "....XXX....",
    "XX..XXX..XX",
    ".XXXXXXXXX.",
    "..XXXXXXX..",
    "...XXXXX...",
    "..XXXXXXX..",
    ".XXXXXXXXX.",
    "XX..XXX..XX",
    "....XXX....",
    "....XXX....",
  ],
} as const

export type ServiceIconName = keyof typeof SERVICE_GLYPHS

export function ServiceIcon({ service, dot = 2, className }: {
  service: ServiceIconName
  dot?: number
  className?: string
}) {
  return <DotPattern rows={SERVICE_GLYPHS[service]} dot={dot} className={`service-icon${className ? ` ${className}` : ""}`} />
}

export default ServiceIcon
